# Generated by Django 5.0.6 on 2024-06-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0003_remove_task_due_date_remove_task_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default='2024-06-19T10:19:09.312102+00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default='2024-06-19T10:19:19.636098+00:00', max_length=255),
            preserve_default=False,
        ),
    ]
